---
# ========================================
# Handlers: proxy (Traefik)
# ========================================

- name: Restart traefik
  community.docker.docker_compose_v2:
    project_src: "{{ storage.ansible.compose }}/traefik"
    state: restarted
  listen: Restart traefik

- name: Reload traefik config
  ansible.builtin.command:
    cmd: docker exec traefik traefik healthcheck --ping
  changed_when: false
  failed_when: false
  listen: Reload traefik config
